owners:
  - LupusLeaks YT
  - Ninja
  - YourUserName

status:
  avatar: CID_337_Athena_Commando_F_Celestial
  status: "\U0001f60d\U0001F975\U0001F449 https://ezfn.net\U0001F975"

commands:
  prefix:
    - "!"
    - /
  case_insensitive: true
  only_owners: false

friends:
  invite_on_added: true
  accept_all_requests: true
  decline_all_requests: false
  invite_on_startup: true
  add_on_removed: true

party:
  dont_leave_if_owner_in_party: true
  join_on_invite: false
  join_if_party_is_empty: true
  
  add_all_members_on_join: true

turn_on: true
