owners:
  - ArticWolf_25
  - BellaJamie101
  - ArticWolf_25

status:
  avatar: CID_017_Athena_Commando_M
  status: "\U0001f60d\U0001F975\U0001F449 https://ezfn.net\U0001F975"

commands:
  prefix:
    - "!"
    - /
  case_insensitive: false
  only_owners: false

friends:
  invite_on_added: true
  accept_all_requests: false
  decline_all_requests: true
  invite_on_startup: true
  add_on_removed: true

party:
  dont_leave_if_owner_in_party: true
  join_on_invite: true
  join_if_party_is_empty: true
  
  add_all_members_on_join: false

turn_on: true
